##基本信息##=====================

#根路径
#baseurl: /
author: Leafer
domain: leafer.tk
encoding: utf-8


### URL配置
url:
  #base path 使用同baseurl，主要用于post.url
  #eg: /test,/doc,http://www.test.com 最后不要/
  bpath: 

  # asset path 资源根路径
  apath: /asset
  theme: /theme/dark

  #post img path
  pipath: /post_rs/img

##导航栏配置
nav_urls: 
  Tag: /tag.html
  存档: /archive.html
  留言: /guestbook.html

img:
  #图片查看效果控件
  imgZoomType: fancybox

##站点配置信息##========================
LF:
  #网站名称
  name: Leafer

  #作者信息
  author: Leafer

  #评论系统配置


  #流量分析配置


  #分享功能配置



##Jekyll配置信息##========================
#markdown引擎
markdown: redcarpet
redcarpet:
  extensions:
    - hard_wrap #硬回车
    - no_intra_emphasis
    - autolink #自动生成链接
    - strikethrough
    - fenced_code_blocks #~~~代码块
    - tables #表格支持

#开启语法高亮插件
pygments: true

#生成静态内容时滤去下列不必要的文件
exclude: ["Gemfile", "Gemfile.lock","README.md"]


#生成的页面URL形式
permalink: /:year/:month/:day/:title.html

#分页设置项
paginate: 5
paginate_path: /page:num



