##基本信息##=====================

#根路径
#baseurl: /
author: Leafer
domain: leafer.tk
encoding: utf-8

layoutTheme: origin

### URL配置
url:
  #base path 使用同baseurl，主要用于post.url
  #eg: /test,/doc,http://www.test.com 最后不要/
  bpath: 

  # asset path 资源根路径
  apath: /asset
  theme: /theme/origin

  #post img path
  pipath: /post_rs/img

##导航栏配置
nav_urls: 
  Leafer: /index.html
  标签: /tag.html
  存档: /archive.html
  留言: /guestbook.html

img:
  #图片查看效果控件
  imgZoomType: fancybox

##站点配置信息##========================
LF:
  #网站名称
  name: Leafer

  #作者信息
  author: Leafer

  #评论系统配置


  #流量分析配置


  #分享功能配置



##Jekyll配置信息##========================
#markdown引擎
markdown: redcarpet
redcarpet:
  extensions:
    - underline # _用于生成下划线
    - superscript # ^用于生成上标
    #- space_after_headers # ##后面必须有空格
    #- lax_spacing 是否需要空行（情况特殊）
    - strikethrough #  ~~删除线
    - disable_indented_code_blocks #禁用四个空格生成代码块
    #- autolink #自动生成超链接
    #- fenced_code_blocks # ~~~html或```html 生成代码块 jekyll中默认true
    - tables # 生成表格
    #- no_intra_emphasis # 禁用单词内的下划线解析
    ## V3才支持的extensions：footnotes, highlight, quote
    #----# render_options：[:filter_html, :no_images, :no_links, :no_styles, :safe_links_only, :with_toc_data, :hard_wrap, :prettify, :xhtml]
    - hard_wrap #硬回车
    #--------# jekyll添加的extensions选项
    #- smart #属于redcarpet，但不是extensions，http://daringfireball.net/projects/smartypants/


#开启语法高亮插件
pygments: true

#生成静态内容时滤去下列不必要的文件
exclude: ["Gemfile", "Gemfile.lock","README.md","Rakefile","log.md"]


#生成的页面URL形式
permalink: /:year/:month/:day/:title.html

#分页设置项
paginate: 15
paginate_path: /page:num



