# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yevon's Blog
description: > # this means to ignore newlines until "baseurl:"
    Yevon's Blog | 叶风的博客
    
baseurl: "/" # the subpath of your site, e.g. /blog

# nav_lists:
#   - title: About
#     url: /blog/about.html

# artworks:
#   baseurl: "/artworks"

url: #"" # the base hostname & protocol for your site
repository: #
# site github reop url
github_repo: 
github_repo_tree: 

# language
lang: zh # the language of your site
timezone: Asia/Shanghai

# author
author: "Yevon"
avata_url: 
bio: 
email: 
twitter_username: 
github_username:  
googleplus_username: 
weibo_username: 
douban_username: 
homepage_url: 

## develop
## paginate
paginate: 7
paginate_path: /page:num
# Basic settings
excerpt_separator: <!--more-->
# Build settings
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
permalink: date

# collections:
#     posts:
#         output: true
#         permalink: /posts/:year/:month/:day-:title/ #

# google analytics
ga_tracking_id: 
# comment
duoshuo_shortname: 
# leancloud vies
app_id: 
app_key: 
app_class: 
# plugins
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-paginate
# server
server_url: "0.0.0.0"
debug: false

## old config
img:
  #图片查看效果控件
  imgZoomType: fancybox

#生成静态内容时滤去下列不必要的文件
exclude: ["Gemfile", "Gemfile.lock","README.md","Rakefile","log.md"]
